# Generated by Django 3.2.6 on 2021-08-31 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('2', 'INACTIVE'), ('3', 'DIED')], default='1', max_length=2)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.hitman')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hitman',
                'db_table': 'hitman',
            },
        ),
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('1', 'ASSIGNED'), ('3', 'FAILED ASSIGNED'), ('4', 'COMPLETED')], default='1', max_length=2)),
                ('date', models.DateField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hits_assignee', to='api.hitman')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hits_created_by', to=settings.AUTH_USER_MODEL)),
                ('hitman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hits_hitman', to='api.hitman')),
            ],
            options={
                'verbose_name': 'Hits',
                'db_table': 'hits',
            },
        ),
    ]
