# Generated by Django 3.2.6 on 2021-08-31 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hits',
            name='hitman',
        ),
        migrations.AddField(
            model_name='hitman',
            name='hits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hitman_hits', to='api.hits'),
        ),
        migrations.AddField(
            model_name='hitman',
            name='rol',
            field=models.CharField(choices=[('1', 'HITMAN'), ('2', 'MANAGER')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='hitman',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hitman'),
        ),
        migrations.AlterField(
            model_name='hitman',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hits',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hits',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hits_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
