# Generated by Django 3.2.6 on 2021-08-31 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210831_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hits',
            options={'verbose_name': 'Hit'},
        ),
        migrations.RemoveField(
            model_name='hitman',
            name='hits',
        ),
        migrations.AddField(
            model_name='hits',
            name='hitman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hits_hitman', to='api.hitman'),
        ),
        migrations.AlterField(
            model_name='hits',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hits',
            name='status',
            field=models.CharField(choices=[('1', 'ASSIGNED'), ('2', 'FAILED ASSIGNED'), ('3', 'COMPLETED')], default='1', max_length=2),
        ),
    ]
