# Generated by Django 3.2.6 on 2021-09-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210831_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hits',
            name='assignee',
        ),
    ]
